### ISSUE TITLE
[김용범] simfetcher

### ISSUE THREAD

**Issue by yongbum94** [FC-InnerCircle/fe1-library#10]
## 프로젝트 이름

simfetcher

## 개요

쉽게 사용할 수 있는 fetch 라이브러리

## 저장소 주소

[yongbum94/simfetcher](https://github.com/yongbum94/simfetcher)

## npm 주소

[npm/simfetcher](https://www.npmjs.com/package/simfetcher)

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] API 명세서 작성 
  - [x] 라이선스 표기
- [x] 기능 구현
  - [x] index(main파일) jsdoc 주석 작성
- [x] 테스트 추가 (라인 커버리지 60% 이상)
  - [x] MSW 세팅 및 활용 
- [x] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
이 프로젝트를 고르는 분이 많네요 :) 인터페이스 설계할 때는 jQuery의 $.ajax, axios 등이 참고할만 합니다.

**Comment by taggon** [comment]
- 👍 msw를 사용한 테스트: 실제 사용과 가까워서 좋습니다.
- `_`를 앞에 붙인 값은 private 필드를 의미한 걸로 보이는데 그렇다면 `_headers`를 확인하도록 테스트를 작성하시면 안됩니다. 프라이빗 메서드와 프라이빗 필드는 다른 메서드를 확인하는 과정에 테스트가 되어야지 직접적인 테스트 대상이 되면 안됩니다. msw 서버로 요청을 보낸 다음에 서버에서 헤더를 확인하는 방법도 있을테고요.
- get이 아닌 다른 method는 테스트가 없습니다.
- 테스트 순서상 `create() return Request Instance` 테스트가 `simfetch.create()`를 호출하는 `header() must set http header` 테스트보다 앞에 오는 게 나중에 문제가 생겼을 때 버그를 찾기가 더 쉽지 않을까요?
- 응답 데이터는 json만 가능한가요? 서버에서 plain text 타입을 반환하면 어떻게 되나요?
- 요청 중단은 가능한가요?
- Request 클래스에 get, post, put, delete 등 각각의 메서드가 존재할 이유가 있었을까요?
- BaseRequest는 abstract method가 하나도 없는데 abstract class로 작성된 이유가 있나요?
- 추상 클래스는 어떻게 활용할 계획이었을까요?
- README의 설명을 보기가 힘듭니다. 특히 API 섹션은 어떤 의미인지 알기가 어렵습니다.

**Comment by yongbum94** [comment]
중간에 상의없이 컨셉을 변경하고 진행한 것 같아 죄송합니다. (__)

전에 주신 댓글을 보고 이유있는 코드를 작성하기위해 노력했습니다.

커버리지
![image](https://github.com/user-attachments/assets/b5f3e9d5-227c-4dde-81e2-28a11d43fde9)

아쉬웠던 부분
- 타입을 좀더 DRY하게 작성하거나 효율적으로 관리할 수 있는 방법이 더 있을 것 같다고 생각합니다.
- 테스트 코드를 작성하는데 있어서 미숙한 부분이나 어색한 부분이 많은 것 같습니다. 

추가적으로 요청중단은 컨셉과 맞지않다고 생각되어서 포함하지 않았습니다.
