### ISSUE TITLE
[염시온] sim-fetch

### ISSUE THREAD

**Issue by sionyeom** [FC-InnerCircle/fe1-library#11]
## 프로젝트 이름

sim-fetch

## 개요

fetch를 조금 더 편하게 사용할 수 있는 래퍼: post, get 등으로 명시. get(url).json<T>(), post(url).json<T>() 등과 같이 타입을 지원하는 json 메서드.

## 저장소 주소

https://github.com/sionyeom/simple-fetch

## npm 주소

[sim-fetch](https://www.npmjs.com/package/sim-fetch)

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
똑같은 프로젝트를 고르는 분이 많아서 어쩔 수 없이 같은 피드백을 드리게 되는데... 인터페이스를 설계할 때는 jQuery의 $.ajax, axios 등을 참고하는 것도 좋습니다.

**Comment by sionyeom** [comment]
<img width="527" alt="스크린샷 2024-08-10 오전 9 30 37" src="https://github.com/user-attachments/assets/779c1759-200a-4ace-987f-c758ed4dc81c">

**Comment by sionyeom** [comment]
피드백 적용 리스트
- success, error handling 제거
- Abortcontroller 기능 활용
- body를 json.stringify()화 하여 요청
- header를 포함 요청
    - default header 지정
- jsdoc 작성
