### ISSUE TITLE
[이호찬] image-uploader

### ISSUE THREAD

**Issue by lhc0506** [FC-InnerCircle/fe1-library#15]
## 프로젝트 이름

tiny-image-uploader

## 개요

이미지를 선택, 크롭, 리사이즈, 파일 크기에 따른 제한이 가능한 라이브러리 또는 컴포넌트

## 기본기능
- 이미지 선택, 크롭, 리사이즈, 파일 크기 제한

## 추가기능
- text 추가

## 저장소 주소

[저장소 링크](https://github.com/lhc0506/tiny-image-uploader)

## npm 주소

[npm 링크](https://www.npmjs.com/package/tiny-image-uploader)

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [ ] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
원아영님과 같은 주제인데 아마 1주 안에 전부 구현하기는 어려울 것으로 예상합니다. MVP 마일스톤을 정해두고 시간이 남으면 2주차에 추가 기능을 구현하는 걸로 계획하면 좋을 것 같습니다.
