### ISSUE TITLE
[유승완] React에서 Form을 쉽게 다루는 라이브러리

### ISSUE THREAD

**Issue by Seung-wan** [FC-InnerCircle/fe1-library#18]
## 프로젝트 

react-form-tiny

## 개요

웹 애플리케이션을 구현하다보면 반드시 사용하게 되는 UI에는 Form이 존재합니다.
React에서는 Form을 다루기 위해 필연적으로 boilerplate들이 많이 생길 수 밖에 없는데요.
이를 추상화하고 native api를 해치지 않는 방식으로 DX까지 신경써서 Form을 쉽게 다룰 수 있도록 합니다.

## 저장소 주소

[링크](https://github.com/Seung-wan/react-form-tiny)

## npm 주소

퍼블리싱이 완료된 후 이슈를 업데이트하여 npm 주소를 남겨주세요

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [ ] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
스펙 정하기가 어려우실 것 같은데 일단은 작게 진행해보세요. 요즘은 Headless 형태의 폼 라이브러리가 많은 것 같은데 한 번 참고해보시면 좋을 것 같습니다. React Hook Form, Tanstack Form 등을 확인해보세요. 😄
