### ISSUE TITLE
[심단비] Vue Hangul Typing

### ISSUE THREAD

**Issue by dvlpDana** [FC-InnerCircle/fe1-library#19]
## 프로젝트 이름

vue-hangul-typing

## 개요

한글 자음, 모음 결합에 타이핑 효과를 제공하는 Vue.js 컴포넌트 입니다.

- 커스터마이징 가능한 타이핑 속도 및 간격
- 사람처럼 보이는 타이핑 효과
- 새 텍스트 추가 옵션
- 애니메이션 반복
- 사용자 정의 스타일 및 클래스 적용

## 저장소 주소

[https://github.com/dvlpDana/vue-hangul-typing](https://github.com/dvlpDana/vue-hangul-typing)

## npm 주소

퍼블리싱이 완료된 후 이슈를 업데이트하여 npm 주소를 남겨주세요

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [x] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
- 동영상 사용법 👍 
- `hangulHelper.ts`의 초성 배열에서 as const를 활용하면 굳이 별도로 타입을 선언하지 않아도 됩니다. 중성, 종성도 마찬가지입니다.
  ```ts
  const CHO = [ "ㄱ", ... ] as const;
  export type Cho = typeof CHO[number];
  ```
- 한글 처리 부분의 로직이 너무 hangul-js와 유사합니다. 심지어 불필요하고 비효율적인 처리까지 닮았어요. 의존성이 가능한 없었으면 좋겠다고 말씀드린 건 나름대로 고민을 해보시라는 의미였지 그대로 옮기라는 뜻은 아니었습니다. 조금 손 보신 것 같은 부분은 보이지만 조금 더 고민을 해보시면 어떨까요.
- `as T` 형태를 많이 쓰는 경향이 있습니다. 어쩌다 필요한 경우가 있기는 한데 지금처럼 많이 사용할 필요도 없고 타입스크립트를 사용하는 의미가 퇴색됩니다. 예를 들어, `is`를 사용해서 범위를 좁힐 수도 있습니다.
  ```ts
  const CHO = [
    'ㄱ', 'ㄲ', 'ㄴ', 'ㄷ', 'ㄸ',
    'ㄹ', 'ㅁ', 'ㅂ', 'ㅃ', 'ㅅ', 'ㅆ',
    'ㅇ', 'ㅈ', 'ㅉ', 'ㅊ', 'ㅋ', 'ㅌ',
    'ㅍ', 'ㅎ'
  ] as const;
  type Cho = typeof CHO[number];
  
  let cho: Cho | undefined;
  
  function isCho(c: string): c is Cho {
    return CHO.includes(c as Cho);
  }
  
  const str = "ㄱㅏㅇㅅㅏㄴ";
  str.split('').forEach(s => {
    if (isCho(s)) {
      cho = s;
    }
  });
  ```
- `as`를 많이 사용하고 있다면 타입을 잘못 정한 건 아닌지 고민이 필요합니다. 예를 들어, `disassembleHangul` 함수는 사용할 때마다 `as`로 형변환을 하고 있는데 이 함수의 타입에 이중배열이 포함되는 게 맞는 걸까요?
- 이건 질문인데 Vue 컴포넌트는 작업하신 것처럼 `ref`를 사용해서 method를 내보내는 게 일반적인 패턴일까요? 자주 보던 사용법은 아닌 것 같아 보이고, prop 하나로 제어가 가능한 정도의 기능일 것 같은데 이렇게 작성하신 이유가 궁금합니다.
- 반복되는 코드는 함수로 묶던지 혹은 다른 방법을 고민해보는 게 좋을 것 같습니다. `typingInterval`를 제거하는 부분이 동일하게 수차례 반복되는데 그대로 복사해서 사용하고 계시네요. 동일한 코드가 수차례 반복된다면 리팩토링을 고민해보세요. 예를 들어 `setInterval`을 래핑해서 다음과 같이 사용하는 방법도 있습니다(제안을 하는 거지 그대로 하라는 의미는 아닙니다).
   ```ts
    const createInterval = (callback, interval) => {
        const timeout = setInterval(() => callback(clean), interval);
        const clean = () => clearTimeout(timeout);
        return clean;
    };
    ...
    cleanInterval = createInterval((clean) => { ... 필요하면 clean 실행하여 인터벌 종료 ... }, interval);
    ...
   // 제거할 때는 함수 한 번만 실행
   cleanInterval?.();
   ```

**Comment by dvlpDana** [comment]
타입스크립트가 아직 익숙하지 않아 타입을 지정하는데 에러가 생겨서 에러를 없애는데만 급급해서, 자세히 코드를 들여다보고 잘못된게 없었는지 확인하는게 부족했던거 같습니다! as 로 타입을 처리하는 부분을 최소화 하려고 했는데 많이 사라지지는 않은 거 같습니다;;

Haungul.js를 사용했었을 때는 한글이 잘 분해되고 합쳐졌는데, 어디서 잘못되었는지 디버깅을 하다가 점점 더 Hangul js의 코드를 그대로 가져와 쓰려고 한 거 같습니다. 불필요한 코드는 걷어내고 필요한 코드만 남겨두었습니다!

vue에서 return한 함수에 접근할 때, ref를 사용합니다. 물론 태곤님이 말씀하신 것처럼 자주 사용되는 패턴은 아닙니다. 처음에는 타이핑 컴포넌트가 특정 동작(예: 타이핑 효과의 일시정지 및 재개)을 수행해야 하고, 이 동작이 외부에서 트리거될 필요가 있는 경우 ref를 사용하는게 맞다고 판단했습니다. 하지만 태곤님의 말씀을 듣고 보니 캡슐화에 위배된 동작을 하게 했다는 걸 깨달아서 props로 관리하도록 수정하였습니다.

그리고 캡슐화에 위배되지 않으면서 자식의 event에 접근하게 할 수 있는 기능이 있으면 좋겠다고 생각하여 typing-start, typing-end 이벤트를추가하였습니다. 

꼼꼼하게 봐주시고 피드백해주시니 놓치는 부분을 알게 되어 성장에 도움이 많이 됩니다 태곤님! 늦은 시간까지 꼼꼼하게 피드백 해주셔서 정말 감사합니다 😊

**Comment by taggon** [comment]
- 사실 이 라이브러리의 강점은 한국어를 '진짜같이' 구현했다는 건데, 그 부분이 조금 더 강조되면 좋을 것 같습니다. 보통은 한글 입력의 단점으로 얘기하는 소위 [도깨비불 현상](https://namu.wiki/w/%EB%8F%84%EA%B9%A8%EB%B9%84%EB%B6%88%20%ED%98%84%EC%83%81)을 살린 게 포인트니까요.
- 패키지 이름이 조금 긴데, 혹시 다른 이름을 고려하신 건 없나요 ㅎㅎ
- vue는 peerDependencies에 들어가야 할 것 같네요.
- 타입만 임포트 할 때는 `import { type Cho, type Jung, type Jong, CHO, JUNG, JONG, type HangulChar } from "@/HangulTypes";`으로 쓸 수도 있습니다. 타입이 필요할 때만 가져오고, 트랜스파일러가 빠르게 무시할 수 있어서 더 좋아합니다.
- `function _isCho(c: string): c is Cho {`를 함수 시그니처로 두고 98라인에서 `} else if (_isCho(char)) {`라고 써도 되지 않을까요? 이렇게 사용하면 해당 블럭에서 `char as Cho`를 `char`로 바꿀 수 있습니다. 지금은 굳이 코드로 한 번 변환한 뒤, 다시 isCho에서 문자열로 변환하는 과정을 거치고 있습니다.
- `result.push("\b" as HangulChar);`에서 `as HangulChar`가 필요한 걸까요?
- 혹은 애초에 `HangulChar` 타입이 필요한 걸까요? 이미 HangulChar는 string과 같은 타입이 되버렸어요. `export type HangulChar = Cho | Jung | Jong | "\b" | "\n" | string;` 이렇게 선언하면 앞에 있는 다른 타입이 모두 string의 서브셋이라서 결국 HangulChar는 string과 같은 같은 의미가 됩니다.
- 아직도 많은 `as`를 없앨 수 있습니다.
- 패키지 자체는 거의 완성 단계에 있는 것 같아서 드리는 🎉추가 미션🎉입니다. vite+vitest로 개발 환경을 바꿔보세요.

**Comment by dvlpDana** [comment]
안녕하세요 태곤님! 저번 주말에 개인 사정으로 인하여 출석을 못해서 무척 아쉽습니다 ㅠ 태곤님께 리뷰도 직접 받고 다른 분들이 만든 라이브러리 소개 타임도 직접 들어볼 수 있었을텐데 사정상 참석하지 못했습니다ㅠㅠ 

올려주신 리뷰사항 반영하여 코드를 수정했습니다! 일단 패키지 이름을 hangul typing으로 짧게 변경하였습니다. 그리고 type을 import할 때, import { type Cho, type Jung, type Jong } 이렇게 import 해올 수도 있다는 꿀팁도 함께 알려주셔서 감사합니다 :) 타입스크립트도 좀 더 공부를 해야겠습니다! 
그리고 HangulChar은 처음에 type을 좀 엄격하게 하고자 만들었었는데, 라이브러리를 만들면서 생각해보니 props로 받은 text가 한글이 아닌 경우도 있겠다 싶어서 string을 추가했었습니다. 좀 더 차분히 생각을 해봤다면 type 자체를 없앨 수 있었을 텐데 놓쳤던 부분이었습니다! 알려주셔서 감사합니다 :) 확실히 불필요한 type이 빠지니 as가 많이 줄었습니다. 
마지막으로 추가미션도 해보았습니다! 확실히 vite가 빠르네요 😀😀 jest와 문법도 거의 동일하여 테스트 코드 자체는 크게 수정하지 않아도 되었습니다! 

태곤님의 피드백을 받으면서 아직까지는 놓치고 있는 부분이 많다고 생각됩니다..;; 하지만 태곤님의 섬세한 피드백을 통해 점점 더 발전해나가는 코드를 보니 뿌듯합니다!ㅎㅎ 이후 과제들부터는 태곤님만큼은 아니지만... 좀 더 꼼꼼하고 세심하게 생각하면서 코드를 작성해봐야겠다고 반성했습니다 ㅎㅎㅎ 감사합니다 태곤님!

**Comment by taggon** [comment]
vite가 React와도 좔 붙지만, 처음부터 Vue와 함께 사용하려고 만든거라 (아예 창시자가 같으니까요) Vue와 함께 사용할 때 더 좋습니다 ㅎㅎ Vitest도 아예 처음부터 Jest와 호환되는 것을 목표로 했었고요. 😄 

코드 자체는 이제 잘 다듬어 진 것 같습니다. 살짝 아쉬운 부분이 있다면, 아래와 같이 초중종성을 변경하는 코드가 많은데요:

```ts
cho = char;
jung = undefined;
jong = undefined;
```

이걸 destructive assignment를 활용해서

```ts
[cho, jung, jong] = [char, undefined, undefined];
// 또는
[cho, jung, jong] = [char, , , ];
```

로 변경하면 코드가 조금 더 보기 좋아질 것 같습니다.

README에도 충분한 정보가 담겨있어서 좋습니다. 지난 주말에 다른 분들이 했던 활동처럼 단비님이 작성하신 라이브러리를 혼자서라도 소리 내어 소개하는 시간을 가져보시면 좋겠습니다. 경력직이라면 적어도 내가 만든 코드와 프로젝트는 자신 있게 설명할 수 있어야 합니다. 연습해두시면 언제가 됐든 도움이 될 거라고 생각합니다. 😄 

제가 드릴 피드백은 여기까지 입니다. 완성도가 어느 정도 생기고 나니까 드릴 피드백이 많지는 않네요. 

수고하셨습니다!
