### ISSUE TITLE
[원아영] 이미지 파일 업로더

### ISSUE THREAD

**Issue by AyoungWon** [FC-InnerCircle/fe1-library#2]
## 프로젝트 이름

pic-pik

## 개요

이미지를 선택, 크롭, 리사이즈, 파일 크기, 확장자에 따른 제한이 가능한 이미지 업로더

### 기본 기능
- 모든 제한 사항을 통과한 이미지에 대한 blob 데이터 및 이미지에 관한 meta정보를 불러올 수 있음

### 1주차 목표
- 원하는 이미지 파일 확장자를 제한할 수 있음
- 이미지 파일의 width, height, 용량을 제한할 수 있음

### 2주차 목표
- 이미지 선택 후 크롭할 수 있음(원형, 사각형)
- 이미지 크롭(또는 원본 이미지 선택) 이후 개발자가 정한 사이즈로 리사이즈 할 수 있음
- 크롭 및 리사이즈후 이미지를 미리보기 할 수 있음
- 처리된 이미지의 파일 사이즈를 제한 할 수 있음

## 저장소 주소

[저장소 링크](https://github.com/AyoungWon/simple-image-uploader)

## npm 주소

[@pic-pik/core](https://www.npmjs.com/package/@pic-pik/core)
[@pic-pik/react](https://www.npmjs.com/package/@pic-pik/react)

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [x] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
기능이 많아서 일주일 안에 하기 어려울 것 같습니다.
첫 주에 어느 기능까지 지원할 것인지 마일스톤을 세우는 건 어떨까요? 일단 릴리스 한 후에 다음 기능을 추가해도 좋습니다. 😄

**Comment by AyoungWon** [comment]
> 기능이 많아서 일주일 안에 하기 어려울 것 같습니다. 첫 주에 어느 기능까지 지원할 것인지 마일스톤을 세우는 건 어떨까요? 일단 릴리스 한 후에 다음 기능을 추가해도 좋습니다. 😄

@taggon 아 2~3주차 프로젝트여서 2주 동안 하는거라고 생각했어요 ㅎ.....일단 기본 기능에 추가 기능 1,2개 정도로 해봐야겠네요!

**Comment by taggon** [comment]
2주에 하는 게 맞긴 한데... 후반 1주는 아마 앞서 나온 버그 수정하고 피드백 반영하느라 바쁘실 걸로 예상됩니다. 다 하시고도 시간이 남으면 그때 추가 기능 구현하셔도 되고요. 아영님은 이대로 진행하셔도 될 것 같습니다! 🚢

**Comment by AyoungWon** [comment]
@taggon 넵! 해당 부분 고려해서 1주동안 어디까지 목표로할지 함께 수정해놓겟습니당!

**Comment by AyoungWon** [comment]
주차별 목표 추가 기능, 프로젝트 이름 수정

**Comment by AyoungWon** [comment]
![스크린샷 2024-08-02 오후 5 43 26](https://github.com/user-attachments/assets/fad69409-1a91-432d-bd6b-3170c30b12ee)

테스트코드 라인커버리지 체크

**Comment by AyoungWon** [comment]
### 1주차 피드백(개선필요사항)
- 제로 dependency로 만들기
- 프로퍼티의 이름 명시적으로 바꾸기 (ex, validateOptions => limit, size => bites)
- examples형식을 온전한 프로젝트 형식으로 만들어주기
- readme에 프로퍼티에 대한 상세한 설명과 예시 추가, 타입 정의, 관련 내용에 링크 엮어주기
- vite + vitest 조합으로 업데이트하기
- e2e 테스트 추가하기

**Comment by AyoungWon** [comment]
@taggon 안녕하세요! 태곤님

제가 지난주 토요일에 이어서 코드 수정할 부분, 테스트코드 추가할 부분, readme 보완할 부분까지 해서 코드 업데이트를 하였는데요.
얘기드렸던거랑 다른점은 제가 주요 기능에 대해 vitest에서 cypress e2e테스트를 진행하겠다고 말씀드렸었는데,  react-router-dom과 페이지를 테스트만을 위해 굳이 추가하고 싶지는 않았어서,  e2e테스트말고 컴포넌트 테스트로 충분한 것 같아 cypress로 컴포넌트 테스트 진행했습니다. 

예전에 제가 need review 라벨을 붙인적이 있었는데, 아직 미완성인 것 같아서 제가 중간에 지웠었거든요.
그래도 배포하기전에 태곤님 리뷰를 받아보고 싶어서 리뷰요청 드립니다🙇🏻‍♀️

**Comment by AyoungWon** [comment]
core/react로 나눠서 배포 완료
