### ISSUE TITLE
[최혜진] simple-webcrypto

### ISSUE THREAD

**Issue by hyejinc-dev** [FC-InnerCircle/fe1-library#20]
## 프로젝트 이름

simple-webcrypto

## 개요
Web Crypto API를 이용해 AES, RSA알고리즘의 암호화, 복호화, SHA, MD5 암호화를 지원하는 패키지

## 저장소 주소
https://github.com/chj93/simple-webcrypto.git

## npm 주소
https://www.npmjs.com/package/simple-webcrypto

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
  - [x] 기본 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [x] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by hyejinc-dev** [comment]
* 기본기능 구현 coverage test
<img width="547" alt="스크린샷 2024-08-05 오후 6 08 48" src="https://github.com/user-attachments/assets/bff1b8f2-831d-4d4e-b8aa-db05fe8c2ab9">

**Comment by hyejinc-dev** [comment]
@taggon 안녕하세요 태곤님! `needs review` 레이블을 추가 하고싶은데 권한이 없는듯합니다ㅠ 우선 최소한의 기본 기능만 구현했습니다. 피드백 부탁드려도 될까요??

**Comment by taggon** [comment]
레이블 추가 권한은 드렸습니다. 확인해보세요. :)

구현이 상대적으로 단순한 편이라 피드백 할 부분이 많지는 않네요 -0-
- 브라우저도 같은 API를 지원하는데 브라우저에서는 사용할 수 없는 모듈일까요?
- 혹시 브라우저도 지원한다면 isomorphic 할까요? 다시 말해, 환경과 관계없이 동일한 결과가 보장될까요?
- 키페어가 달라지면 RSA 인크립트된 값도 달라지는지 테스트가 필요하지는 않을까요?
- 테스트 설명은 기대값을 정확하게 작성해주세요. 그러니까 `it("should encrypt and decrypt correctly", ...` 보다는 `it("should yeild  decrypted text that is exactly the same as the original text", ...` 와 같은 식으로 작성할 수 있습니다.
- 기능이 두 가지이므로 인크립트와 디크립트는 분리해서 테스트하면 좋을 것 같습니다. 디크립트에서 인크립션을 다시 반복하더라도 우선은 인크립션만 테스트하는 것입니다. 이와 같은 방식으로 테스트가 깨졌을 때 어느 부분이 정확히 문제인지 탐지하기가 더 편해집니다. 예를 들어 지금의 rsa 테스트의 경우, 테스트가 실패한다면 인크립션이 문제인지 디크립션이 문제인지 알기 어렵습니다.
- 영어가 아닌 다른 문자(CJK, 이모지 등)도 지원하나요?
- 다음 확장 계획이 있을까요?

**Comment by hyejinc-dev** [comment]
피드백 감사합니다!
영어가 아닌 다른 문자(CJK, 이모지 등)의 경우 `TextEncoder`를 사용하고 있어 지원할 것으로 예상됩니다. 확인 후 text, example 추가 하겠습니다!

우선 피드백 주신 내용 적용 후 확장하겠습니다!

- [x] 다른 문자(CJK, 이모지 등) 지원 확인
  - [x] test 및 example 추가
- [x] 브라우저 환경 사용 지원 (Web Crypto API를 사용하는 공통 모듈 생성)
- [x] 테스트 업데이트
  - [x] 기능별 분리 (인크립트, 디크립트)
  - [x] RSA 테스트 케이스 추가 (키페어가 달라지면 RSA 인크립트된 값도 달라지는지 확인)
  - [x] 테스트 설명 업데이트 (기대값을 정화하게 작성)
