### ISSUE TITLE
[이승준] react-skeleton

### ISSUE THREAD

**Issue by jun0811** [FC-InnerCircle/fe1-library#4]
## 프로젝트 이름

react-skeleton

## 개요

웹 프로젝트에서 사용할 수 있는 프레임워크 독립적인 자동 스켈레톤 생성 제공. 컨텐츠의 예상 크기를 계산하여 로딩 중에 적절한 크기의 스켈레톤 UI를 표시합니다.

## 저장소 주소

[저장소 링크
](https://github.com/jun0811/auto-skeleton)
## npm 주소
https://www.npmjs.com/package/react-tiny-skeleton
## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
- 얼핏 생각하기에는 쉽지 않을 것 같은데 컨텐츠의 예상 크기를 구하는 방식은 어떻게 될까요?
- 프레임워크에 독립적이라는 의미는 코어를 작성한 후 여러 프레임워크용 래퍼를 만들겠다는 의미일까요, 아니면 바닐라 자바스크립트 라이브러리만 작성하겠다는 의미일까요?

**Comment by jun0811** [comment]
> * 얼핏 생각하기에는 쉽지 않을 것 같은데 컨텐츠의 예상 크기를 구하는 방식은 어떻게 될까요?
텍스트, 스타일 정보, 이미지, 레이아웃 정보등을 받아와서 최대크기를 추정해서 해당 크기를 유추해보는 것 해볼 수 있을까 생각해봤는데 어려울 것 같긴합니다..   

> * 프레임워크에 독립적이라는 의미는 코어를 작성한 후 여러 프레임워크용 래퍼를 만들겠다는 의미일까요, 아니면 바닐라 자바스크립트 라이브러리만 작성하겠다는 의미일까요?
코어를 작성하고 여러 프레임워크용 래퍼를 만들어볼려고 합니다 ( 일단 React만 1차로 생각해고 있습니다 )

**Comment by taggon** [comment]
> 코어를 작성하고 여러 프레임워크용 래퍼를 만들어볼려고 합니다 ( 일단 React만 1차로 생각해고 있습니다 )

이 부분은 좋습니다. 👍 

> 텍스트, 스타일 정보, 이미지, 레이아웃 정보등을 받아와서 최대크기를 추정해서 해당 크기를 유추해보는 것 해볼 수 있을까 생각해봤는데 어려울 것 같긴합니다.

사용법도 제가 잘 이해를 못한 것 같은데 혹시 알려줄 수 있나요? 내용으로 봐서는 우리 과정 중에 진행하기 어려울 수 있겠다 싶은데, 그렇다면 다른 프로젝트로 방향을 바꾸는 것도 고려해야 할 듯 합니다.

**Comment by jun0811** [comment]
> 사용법도 제가 잘 이해를 못한 것 같은데 혹시 알려줄 수 있나요? 내용으로 봐서는 우리 과정 중에 진행하기 어려울 수 있겠다 싶은데, 그렇다면 다른 프로젝트로 방향을 바꾸는 것도 고려해야 할 듯 합니다.

가능성이 있다고 생각 했는데 매우 어려운 것 같습니다 ...ㅠㅠ 그냥 평범한 react-skeleton 오픈소스로 주제를 바꿔보는 건 괜찮을까요?
테마와 애니메이션을 사용한 라이브러리도 만들어보고 싶은 생각이 있어서요

**Comment by taggon** [comment]
react-skeleton 좋습니다. 그건 저도 이해가 잘 되네요 ㅎㅎ :)

**Comment by jun0811** [comment]
> react-skeleton 좋습니다. 그건 저도 이해가 잘 되네요 ㅎㅎ :)

넵 감사합니다
