### ISSUE TITLE
[김기철] tiny-placeholder

### ISSUE THREAD

**Issue by kichul7493** [FC-InnerCircle/fe1-library#6]
## 프로젝트 이름

tiny-placeholder

## 개요

원하는 크기와 색상, 글자로 이루어진 플레이스홀더 이미지를 생성하는 라이브러리

## 저장소 주소

[tiny-placeholder](https://github.com/kichul7493/tiny-placeholder)

## npm 주소

[@tiny-placeholder/core](https://www.npmjs.com/package/@tiny-placeholder/core)
[@tiny-placeholder/react](https://www.npmjs.com/package/@tiny-placeholder/react)

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [x] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱
- [x] 클래스 리팩토링 (도형 클래스 분리)
- [x] 분리된 types 제자리 찾기
- [x] Docs 정의 (public 매서드, 라이브러리로 제공되는 부분)
- [x] 프레임워크별 지원을 위해 모노레포로 변경
- [x] github actions을 통한 CI/CD 구축

**Comment by kichul7493** [comment]
캔버스로 이미지를 생성하는 PlaceholderImageGenerator(라이브러리) 클래스의 동작을 테스트할 방법을 잘 모르겠습니다.

샘플 이미지를 생성해놓고 라이브러리 클래스가 생성한 이미지와 비교해서 동일하게 만들어졌는지를 테스트 하는 방법을 생각해봤는데,
이미지 자체를 비교하는 방법이 마땅하지 않을 것 같습니다.

이런 경우 테스트를 어떻게 작성해야 하는지 조언 주시면 감사하겠습니다. 🥲

**Comment by kichul7493** [comment]
![스크린샷 2024-08-08 오후 9 19 35](https://github.com/user-attachments/assets/3fb883e9-774f-434b-af62-fa87ba577a4a)

**Comment by taggon** [comment]
이미 퍼블리싱을 하셔서 npm에 들어가서 찾아봤습니다. 검색해보면 아래와 같이 나타나는데 README 파일을 라이브러리 설명으로 시작하면 어떨까요? 혹은 package.json에 description 필드를 설정해주셔도 됩니다. 😄 

<img width="994" alt="image" src="https://github.com/user-attachments/assets/b26b6929-8134-43da-bdc4-f239cab14f37">

마찬가지로 README에 있는 링크가 npm에서는 깨집니다. 이것도 수정하시면 좋을 것 같습니다.

**Comment by kichul7493** [comment]
안녕하세요 리더님!
npm 배포는 @tiny-placeholder로 수정해두었었는데, 기존 패키지를 삭제하지 않아서 혼동이 있었던거 같습니다.
말씀하신대로 package.json의 description 추가하여 패키지 설명이 잘 나오도록 수정하였습니다.
꼼꼼히 챙기려고 노력했는데, 놓친 부분이 있었네요.
시간내서 확인해주셔서 감사합니다!
