### ISSUE TITLE
[이정중] typing-changer

### ISSUE THREAD

**Issue by Gentlee-dev** [FC-InnerCircle/fe1-library#8]
## 프로젝트 이름

typing-changer
## 개요

한영키를 잊었을때를 위한 
한글=>영어, 영어=>한글 자동 변환
2벌식기준 

## 추가사항
문단을 입력받아 잘못된 부분을 찾고 수정된 값과 함께 객체형태로 반환
ex) 
{ 
    dkssudgktpdy : '안녕하세요' ,
    ㅗㅑ : 'hi'
};

## 저장소 주소

https://github.com/Gentlee-dev/typingchanger-hangul

## npm 주소

https://www.npmjs.com/package/typingchanger-hangul

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [x] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
https://github.com/Gentlee-dev/typingchanger-hangul/blob/cb45686e96dccbff3a12ea9e3e4a85a91121149c/src/com.ts#L240-L247

- 코드 중에 이런 파트가 있는데 for ... of를 썼으면 더 간단하게 만들 수 있습니다.
- for 문 내부에 block scope가 설정되므로 for문 안쪽에서만 사용되는 code1, code2는 for 내부에서 const로 선언해도 됩니다.

다음은 코드를 보고 떠오르는 부분을 순서없이 옮겨보았습니다.

- for 문 내부에서 복잡한 조건문을 사용하는 경우 continue나 break을 사용해서 코드 구조를 더 간단하게 만들 방법은 없었는지 고민이 필요합니다.
- 테스트가 동작하지 않습니다. ... 확인해보니 build 후에 실행해야 하는 거네요.
- build와 watch 모드는 따로 분리해주면 좋습니다.
- 테스트
  - 테스트 수트를 따로 작성하신 이유가 있을까요?
  - 라인 커버리지는 어떻게 측정하셨을까요?
  - 반복 테스트는 어떻게 수행하셨나요?
  - 빌드 된 후의 모듈만 테스트하는 이유가 있을까요?
- JSDoc 설명이 함수에 추가되면 좋을 것 같습니다.
- `{ [idx: string]: string }` 보다는 `Record<string, string>`이 더 읽기 편합니다. 참고로 TS에는 쓸만한 유틸리티 함수가 은근히 많이 내장되어 있습니다. 나중에 기회가 되면 한 번 살펴보면 좋습니다.
-  `forgotConvert` 함수에서 제거하는 특수문자에 어떤 건 포함되고 어떤 건 아닌데 이유가 있을까요?
- `forgotConvert` 함수에서 for 문 내부는 별도 함수로 분리하면 읽기가 더 편합니다. 예를 들어,
  ```ts
  const convertWord = (str: string) => {
    const detectedLang = checkWordLanguage(word);
    if (detectedLang !== 'mix' && detectedLang !== 'other') return;
  
    // 영어인 경우
    if (detectedLang === 'en') {
      const converted = enToKr(word); // 한국어를 변환한 후
  
      // 변환 결과가 올바른 한국어일 때만 반환
      if (getIsCompleteKrWord(converted)) {
        return converted;
      }
    }
  
    if (detectedLang === 'kr') {
      if (!getIsAlwaysConvertKr(word) && getIsCompleteKrWord(word)) return;
      return krToEn(word);
    }
  };
  
  const forgotConvert = (text: string, excepts: string[] = []) => {
    const resultString = text.replace(/[.?!,()]/g, ""); // 특문 제거
    const words = resultString.split(" ");
    const answer: { [idx: string]: string } = {};
  
    for (const word of words) {
      if ([...EXCEPT_WORDS, ...excepts].indexOf(word) !== -1) continue; // 예외단어 제외
  
      const converted = convertWord(word);
      if (converted) {
        answer[word] = converted;
      } 
    }
    return answer;
  };
  ```
- 불리언 값을 반환하는 함수는 대체로 `is` 또는 `has` 등으로 시작하고, 앞에 `get`을 추가하지 않습니다. `Array.isArray`가 좋은 예입니다. 따라서 `getIsCompleteKrWord`는 `isCompleteKrWord`로 바뀌는 게 더 좋은 이름입니다.
- `getIsCompleteKrWord`는 정규식으로 처리하지 않은 이유가 있을까요? 다른 곳에서는 사용한 걸로 보아 정규식을 사용하지 않으려는 의도는 아닌 걸로 이해했습니다.
- 배열을 사용할 일이 많은 코드인데, 조금 더 배열 메서드를 활용하면 좋겠습니다. 예를 들어, 같은 로직을 아래와 같이 줄일 수도 있습니다. 혹시 원래 하셨던 방식대로 작성한 이유가 있는 거라면 알려주세요.
  ```ts
  const krToEn = (word: string) => disassemble(word).map(s => KR_TO_EN[s]).join('');
  ```
- `ALWAYS_CONVERT_KRS`는 어떻게 선정된 목록일까요? 이에 대한 설명이나 규칙도 없고 사용하는 사람이 편집할 방법도 없어서 의문이 드는 부분입니다.
- disassemble 함수가 필요 이상으로 복잡한 것처럼 보이는데 구조를 더 단순화할 수 있을까요?
- disassemble에는 언제 null이 전달되나요? 필요한 방어코드 맞을까요?
- 파일 이름인 `com.ts`의 com은 무슨 의미일까요?
- 파일을 분리한 기준은 어떻게 될까요? 일관적인 규칙이 있으면 알려주세요.
- assemble 함수에 var로 선언한 변수가 있는데 이유가 있나요?
- assemble 함수의 파라미터 타입은 `string[]`인데 코드를 보면 `string`도 들어올 수 있다고 가정하고 있습니다.

**Comment by taggon** [comment]
한글 처리 부분의 로직이 너무 hangul-js와 유사합니다. 심지어 불필요하고 비효율적인 처리까지 닮았어요. 의존성이 가능한 없었으면 좋겠다고 말씀드린 건 나름대로 고민을 해보고 자신의 방식으로 작성해보시라는 의미였지 그대로 옮기라는 뜻은 아니었습니다.

**Comment by Gentlee-dev** [comment]
정성이 담긴 코드리뷰 너무 감사드립니다.
평소 개발할때보다 조금 더 신경써서 진행했는데 그럼에도 부족한 부분이 많음을 다시한번 느끼게 되었습니다.
피드백이나 질문 주신 사항에 대해 답변 드리며, 말씀해 주신 부분 적용하여 다시 리뷰 요청 드리도록 하겠습니다 감사합니다!

---
코드 중에 이런 파트가 있는데 for ... of를 썼으면 더 간단하게 만들 수 있습니다.
for 문 내부에 block scope가 설정되므로 for문 안쪽에서만 사용되는 code1, code2는 for 내부에서 const로 선언해도 됩니다.
build와 watch 모드는 따로 분리해주면 좋습니다.
JSDoc 설명이 함수에 추가되면 좋을 것 같습니다.
{ [idx: string]: string } 보다는 Record<string, string>이 더 읽기 편합니다. 참고로 TS에는 쓸만한 유틸리티 함수가 은근히 많이 내장되어 있습니다. 나중에 기회가 되면 한 번 살펴보면 좋습니다.
forgotConvert 함수에서 for 문 내부는 별도 함수로 분리하면 읽기가 더 편합니다.
for 문 내부에서 복잡한 조건문을 사용하는 경우 continue나 break을 사용해서 코드 구조를 더 간단하게 만들 방법은 없었는지 고민이 필요합니다.
 - 말씀해주신 부분 적용하도록 하겠습니다. 감사합니다! 
 - ts부분은 처음본 부분입니다. 한번 살펴보도록 하겠습니다!
---
테스트가 동작하지 않습니다. ... 확인해보니 build 후에 실행해야 하는 거네요.
빌드 된 후의 모듈만 테스트하는 이유가 있을까요?
 - 노드 v20.11.0을 사용하고 있습니다. ts파일을 실행하려면 ts-node를 사용해야하는데 20버전부터 잘 지원되지 않는다고 하여서 빌드 후 js파일을 사용하고 있습니다.
[참조1](https://stackoverflow.com/questions/76725253/ts-node-and-esm-unknown-file-extension-ts)
[참조2](https://www.inflearn.com/news/1065346?srsltid=AfmBOor8b4m_HP21pVnlO6ma9uFiAHmhdMFD06PpkZnJ-fL-CMpLUVJJ)
---
### 테스트코드를 작성하는게 처음이라서 부족한 부분이 많습니다..ㅠㅠ
테스트 수트를 따로 작성하신 이유가 있을까요?
 - 별도의 라이브러리나 프레임워크들 사용하지 않은 이유를 물으신거라면 제로디펜던시가 너무 욕심이나서 따로 작성하였습니다.
---
라인 커버리지는 어떻게 측정하셨을까요?
 - 라인커버리지를 처음 들어봐서... 요구사항에 있는건 봤는데 잊고있었습니다ㅠㅠ 측정해보고 요구사항에 맞게 수정하겠습니다!
---
반복 테스트는 어떻게 수행하셨나요?
 - 반복 테스트가 어떤건지 리더님께서 말씀하셔서 알게 되었습니다. 현재는 테스트케이스가 담긴 배열을 반복문을 통해서 여러번 테스트를 진행하고있습니다.
혹시 질문에 따로 의도하신 바가 있으신가요?
---
forgotConvert 함수에서 제거하는 특수문자에 어떤 건 포함되고 어떤 건 아닌데 이유가 있을까요?
 - 특수문자가 한 단어의 끝이나 처음이 아닌곳에 들어간 경우 처리하기 힘들어보여서 제외하였으나, 마침표나 물음표가 들어가는 경우가 적지 않음에도 제외되는게 이상해서
제가 생각하기에 단어의 처음이나 끝에 들어가고 자주쓰이는 특수문자를 적용하였습니다.
---
불리언 값을 반환하는 함수는 대체로 is 또는 has 등으로 시작하고, 앞에 get을 추가하지 않습니다. Array.isArray가 좋은 예입니다. 따라서 getIsCompleteKrWord는 isCompleteKrWord로 바뀌는 게 더 좋은 이름입니다.
 - is로 시작하면 함수명 보다는 변수명에 가깝다는 느낌이 들어서 함수임을 명확히 하고자 get을 붙히게 되었습니다. 피드백주신 부분을 통해 생각해보니 요즘은 에디터에서 함수와 변수가 색상이 달라서 구분이 명확하기 때문에 피드백 주신 부분대로 적용하도록 하겠습니다 감사합니다!
---
getIsCompleteKrWord는 정규식으로 처리하지 않은 이유가 있을까요? 다른 곳에서는 사용한 걸로 보아 정규식을 사용하지 않으려는 의도는 아닌 걸로 이해했습니다.
 - hangul.js를 참조하여 구현하다보니 따라하게 되었습니다. 정규식으로 하는게 더 좋은 방법인가요?
---
배열을 사용할 일이 많은 코드인데, 조금 더 배열 메서드를 활용하면 좋겠습니다. 예를 들어, 같은 로직을 아래와 같이 줄일 수도 있습니다. 혹시 원래 하셨던 방식대로 작성한 이유가 있는 거라면 알려주세요.
 - 피드백 감사합니다! 큰 의도가 있지 않았습니다. 기존에 하던 방식이어도 한번 더 생각 해보도록 하겠습니다.
---
ALWAYS_CONVERT_KRS는 어떻게 선정된 목록일까요? 이에 대한 설명이나 규칙도 없고 사용하는 사람이 편집할 방법도 없어서 의문이 드는 부분입니다.
 - [readme](https://github.com/Gentlee-dev/typingchanger-hangul?tab=readme-ov-file#%EC%9E%90%EB%AA%A8%EC%9D%8C-%EC%A1%B0%ED%95%A9%EC%9D%B4-%EC%99%84%EB%B2%BD%ED%95%9C-%ED%95%9C%EA%B8%80%EC%9E%84%EC%97%90%EB%8F%84-%EC%98%81%EC%96%B4%EB%A1%9C-%EB%B3%80%ED%99%98%ED%96%88%EC%9D%84%EB%95%8C-%EC%9D%98%EB%AF%B8%EC%9E%88%EB%8A%94-%EB%8B%A8%EC%96%B4%EC%9D%B8-%EA%B2%BD%EC%9A%B0)를 보시면 선정 이유를 확인 하실 수 있습니다. 편집방법은 추가 구현 하도록 하겠습니다! 감사합니다
---
assemble과 disassemble함수는 말씀해주신대로 hangul.js를 복붙하여 진행하였습니다.
처음부터 hangul.js를 참조하여 직접 구현하려 하였으나 생각보다 신경쓸 부분이 많아서 일단 가져와서 ts화만 진행하였고, 기능 구현 후에 고쳐볼 생각이었습니다. 죄송합니다ㅠㅠ
---
파일 이름인 com.ts의 com은 무슨 의미일까요?
 - 처음에 만들어진 파일이라 어떤 의미로 지었는지 기억나지 않지만 큰 의미는 없을거라 생각됩니다. 리팩토링 할때 의미있는 이름으로 수정하도록 하겠습니다.
---
파일을 분리한 기준은 어떻게 될까요? 일관적인 규칙이 있으면 알려주세요.
- 말씀해주신 부분대로 상수를 따로 분리하였고, hangul.js에서 가져온 부분도 따로 분리하였습니다. 리팩토링 할때 의미를 두어 분리 할 수 있도록 하겠습니다!

**Comment by taggon** [comment]
- ts-node 대신 [tsx](https://www.npmjs.com/package/tsx)는 혹시 사용해보셨을까요?
- 제로 디펜던시는... 개발 환경의 디펜던시까지 포함하는 개념은 아니예요. zero dependency로 검색해서 찾은 [모듈의 예시](https://www.npmjs.com/package/vanjs-core)에서 보듯, package.json으로 말하자면 "devDependencies"는 있어도 되지만 "dependencies"에는 아무 것도 없는 걸 제로 디펜던시라고 합니다.
- 또한 제가 말씀드렸듯이 node 20에는 기본 테스트 수트가 포함되어 있어요.
- 여기서 말한 "반복 테스트"는 코드를 수정하는 중에 테스트가 지속적으로 반복 수행되는 것을 의미했는데, 용어에 혼동이 있을 수도 있었겠습니다. 예를 들어 mocha나 vitest라면 watch 옵션으로 지원하는 그 기능을 의미했습니다. 일일이 수동으로 테스트를 돌리면 생산성이 떨어져요.
- 한글 확인에서 정규식으로 하는 게 늘 좋은 방법인 것은 아니지만, `word.split("").every((spell) => isCompleteHangul(spell.charCodeAt(0)));` 보다는 `/^[가-힣]$/.test(word);`가 더 짧고 명료할 것 같아서 물어봤습니다. 성능도 정규식쪽이 더 나을 것 갈습니다.
- `제가 생각하기에 단어의 처음이나 끝에 들어가고 자주쓰이는 특수문자를 적용하였습니다.` 으음... 기준이 자의적인 것 같습니다. 이 라이브러리를 사용하시는 분들은 특수문자도 보존해주길 바라지는 않을까요?

**Comment by Gentlee-dev** [comment]
ts-node 대신 tsx는 혹시 사용해보셨을까요?
 - 감사합니다ㅠㅠㅠ 빌드없이 실행이 가능해졌습니다ㅠㅠ
---
제로 디펜던시는... 개발 환경의 디펜던시까지 포함하는 개념은 아니예요. zero dependency로 검색해서 찾은 모듈의 예시에서 보듯, package.json으로 말하자면 "devDependencies"는 있어도 되지만 "dependencies"에는 아무 것도 없는 걸 제로 디펜던시라고 합니다.
 - 제로 디펜던시가 그런 의미였군요 ts설치하면서 어쩔수 없는건가 했는데 다시 희망을 얻었습니다!
---
또한 제가 말씀드렸듯이 node 20에는 기본 테스트 수트가 포함되어 있어요.
 - tsx와 함께 적용하였습니다. 감사합니다!!
---
여기서 말한 "반복 테스트"는 코드를 수정하는 중에 테스트가 지속적으로 반복 수행되는 것을 의미했는데, 용어에 혼동이 있을 수도 있었겠습니다. 예를 들어 mocha나 vitest라면 watch 옵션으로 지원하는 그 기능을 의미했습니다. 일일이 수동으로 테스트를 돌리면 생산성이 떨어져요.
 - 기본 내장된 test runner의 watch를 이용하여 구현 하였습니다!
---
한글 확인에서 정규식으로 하는 게 늘 좋은 방법인 것은 아니지만, word.split("").every((spell) => isCompleteHangul(spell.charCodeAt(0))); 보다는 /^[가-힣]$/.test(word);가 더 짧고 명료할 것 같아서 물어봤습니다. 성능도 정규식쪽이 더 나을 것 갈습니다.
 - 감사합니다 정규식으로 바꿔서 구현 해보도록 하겠습니다.
---
제가 생각하기에 단어의 처음이나 끝에 들어가고 자주쓰이는 특수문자를 적용하였습니다. 으음... 기준이 자의적인 것 같습니다. 이 라이브러리를 사용하시는 분들은 특수문자도 보존해주길 바라지는 않을까요?
 - 자료조사를 통해 많이 쓰이는 특수문자를 찾아보도록 하겠습니다.
 - 사용하는 입장에서 키와 밸류를 replace하게 되면 특수문자를 보존하며 바꿀 수 있을거라 생각해서 단어 양끝에 쓰이는 특문은 제외해도 괜찮지 않을까 생각했습니다.

**Comment by Gentlee-dev** [comment]
리더님 질문이 있습니다.

npx tsx --test --experimental-test-coverage를 활용하여 커버리지를 측정해보았습니다.
라인커버리지 88%
브랜치커버리지 75%가 나왔습니다.

우선 test runner에 대해 다시 상기 시켜주신 점 감사의 말씀 드립니다.
많은 도움이 되었습니다.

여쭙고싶은 부분은 저는 한 함수에 대해서만 여러 테스트코드를 작성했습니다.
export하고자 하는 함수였기에 일단 이 함수를 테스트하는게 우선이라고 생각하였으며,
다른 함수들도 추후에 테스트할 계획이었습니다.

리더님께서 커버리지를 언급해주셔서 현재 진행된(한 함수만 테스트된) 커버리지를 측정해본 결과
위와 같은 수치가 나왔으며, 파일별로 수치가 제공됐는데
제가 테스트하지 않은 함수들도 테스트가 진행된걸로 보입니다.

아마 테스트가 진행된 함수를 실행하며 다른 함수들도 실행됐기 때문에 이런 결과가 나왔으리라 예상하는데
그러면 다른 함수들은 굳이 테스트코드를 작성하지 않아도 되는걸까요?

**Comment by taggon** [comment]
@Gentlee-dev 직접 테스트하지 않았어도 다른 모듈을 테스트하는 과정에서 충분히 테스트되었다 판단하면 직접 테스트 코드를 작성하실 필요는 없습니다.

예를 들어 아래와 같이 전달된 두 숫자의 제곱을 더하는 함수 `squareSum`이 있다고 가정해볼게요. 이 함수에서 `square`라는 함수를 호출해서 불러오고 있고, `squareSum`을 테스트하면서 `square`도 충분히 커버가 된 것 같으면 따로 작성하지 않으셔도 됩니다. 공개된 API만 테스트하라고 안내드린 것도 비슷한 맥락입니다.

```ts
export function squareSum(a, b) {
   return square(a) + square(b);
}

function square(num) {
   return num * num;
}

it('인수 순서에 상관없이 동일한 값을 반환한다', ... );
it('음수를 전달하면 절댓값이 같은 양수를 전달한 결과와 같다', ...);
...
```

다만, 커버리지 비율로만 판단하지 마시고 해당 기능이 "충분히 테스트되었나"를 기준으로 삼으면 좋습니다. 라인 커버리지는 1번만 테스트해도 올라가는데 기능 테스트를 하다보면 같은 함수를 몇 번씩 실행해야 할 때가 많거든요.
