### ISSUE TITLE
[윤장원] Fetcher 라이브러리

### ISSUE THREAD

**Issue by jangwonyoon** [FC-InnerCircle/fe1-library#9]
## 프로젝트 이름

Fetcher 라이브러리

## 개요

fetch를 조금 더 편하게 사용할 수 있는 래퍼: post, get 등으로 명시. ```get(url).json<T>()```,  ```post(url).json<T>()``` 등과 같이 타입을 지원하는 json 메서드.

## 저장소 주소

https://github.com/jangwonyoon/fetchey

## npm 주소

[저장소 주소](https://www.npmjs.com/package/fetchey)

## 체크리스트

- [x] 개인 저장소 생성
- [x] README.md 파일 작성 (다음 항목 포함)
  - [x] 프로젝트 개요
  - [x] 설치 방법 / 사용 방법
  - [x] 라이선스 표기
- [x] 기능 구현
- [ ] 테스트 추가 (라인 커버리지 60% 이상)
- [ ] 사용 예제 프로젝트 추가 (examples 폴더 아래에 2개 이상)
- [x] npm 퍼블리싱

**Comment by taggon** [comment]
이왕 만드는 라이브러리니까 짧고 기억하기 쉽게 지어보는 건 어떨까요? `ezreq` (easy request) 라거나 `goodfetch`, `fetchey` 등을 생각해봤는데... 좀 애매하긴 하네요 ^^;;
인터페이스에 관해서는 jQuery의 $.ajax, axios 등이 참고할만 합니다.

**Comment by jangwonyoon** [comment]
@taggon  ```fetchey``` 좋은거 같아요. ```fetchey```로 진행하겠습니다.
